version: '2.1'
services:
    sql:
        build: 
            context: ..\sql
            dockerfile: Dockerfile
        networks:
            default:
                aliases:
                    - sql
    nav:
        depends_on:
            - "sql"
        ports:
            - "7045-7049:7045-7049"
        networks:
            default:
                aliases:
                    - nav
    web:
        build:
            context: ..\nav-web
        depends_on:
            - "nav"
        ports:
            - "80:80"
            - "443:443"
        networks:
            default:
                aliases:
                    - web

networks:
  default:
    external:
      name: nat