version: '2.1'
services:
    sql:
        build: 
            context: ..\sql
            dockerfile: Dockerfile
        networks:
            default:
                aliases:
                    - sql
    nav:
        depends_on:
            - "sql"
        ports:
            - "7045-7048:7045-7048"
        networks:
            default:
                aliases:
                    - nav
networks:
  default:
    external:
      name: nat